# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
    demo_config: 
        database:
            name: "%database_name%"
            user: "%database_user%"
            password: "%database_password%"
            host: "%database_host%"
            port: "%database_port%"
            driver: pdo_mysql
            charset: UTF8

services:
    demo:
        class: Demo\Service\Common\DemoContainer
        arguments: ["%demo_config%"]

    app_asset_helper.twig_extension:
            class: AppBundle\Twig\AssetHelperExtension
            arguments:    ['@service_container']
            public: false
            tags:
                - { name: twig.extension }
